### ISSUE TITLE
Is there any reason why poetry wants python >=3.7 for this package?

### ISSUE THREAD

**Issue by mianos** [post-luxembourg/pypmp#4]
I tried to install it with pip install -e and I only have python 3.6.
I used the pypy package and it works fine but it is missing the add_account.

**Comment by pschmitt** [comment]
There's no reason, besides that we decided to not support older Python versions and won't be testing against them. It should work fine on 3.6, but I cannot guarantee that we won't break anything in the future.

**Comment by mianos** [comment]
Ok thanks. Not much choice for me at work. I'll fork it for my pip install and see how we go.
I just started with PMP. It's odd there is no paging.
Have you noticed errors are reported as a web page and that makes your json() call raise?
